### ISSUE TITLE
1 excel file have over 2 sheets 

### ISSUE THREAD

**Issue by nquang2448** [Apkawa/xlsx2html#12]
Hi, your lib so cool so far. But i dont know how to use it for extract excel file have over 2 sheets. It is just extract 1 sheet in there. Please help me. Thank you so much ^^

**Comment by Apkawa** [comment]
Hello.
Currently you can use

```
# by index
xlsx2html(xlsx_file, out_file, sheet=0) 
# by sheet name
xlsx2html(xlsx_file, out_file, sheet="Sheet 1") 
```

Or use low level api 
```
from xlsx2html.core import worksheet_to_data, render_data_to_html

data = worksheet_to_data(worksheet, locale='en')
html = render_data_to_html(data)
```

**Comment by UshioYu** [comment]
> Hello. Currently you can use
> 
> ```
> # by index
> xlsx2html(xlsx_file, out_file, sheet=0) 
> # by sheet name
> xlsx2html(xlsx_file, out_file, sheet="Sheet 1") 
> ```
> 
> Or use low level api
> 
> ```
> from xlsx2html.core import worksheet_to_data, render_data_to_html
> 
> data = worksheet_to_data(worksheet, locale='en')
> html = render_data_to_html(data)
> ```

Hi, can you give me some ideas about  show only one html to display all sheets?

**Comment by Apkawa** [comment]
Hello. look at function `xlsx2html.core.render_table`
As example

```python
import openpyxl
from xlsx2html.core import worksheet_to_data, render_table

table_html = ""
for ws in openpyxl.load_workbook(filepath, data_only=True).worksheets:
    data = worksheet_to_data(ws, locale='en')
    table_html.append(render_table(data))

html = "<html><body>%s</body></html>" % table_html
```

I will think about a convenient api

**Comment by UshioYu** [comment]
> Hello. look at function `xlsx2html.core.render_table` As example
> 
> ```python
> import openpyxl
> from xlsx2html.core import worksheet_to_data, render_table
> 
> table_html = ""
> for ws in openpyxl.load_workbook(filepath, data_only=True).worksheets:
>     data = worksheet_to_data(ws, locale='en')
>     table_html.append(render_table(data))
> 
> html = "<html><body>%s</body></html>" % table_html
> ```
> 
> I will think about a convenient api

You have my gratitude.
