### ISSUE TITLE
Images disappear in excel 

### ISSUE THREAD

**Issue by kurt-liao** [Apkawa/xlsx2html#15]
Hi, I've some problem about images. 
The problem is that I can't transfer images from excel to html.

**Comment by mgmanalili** [comment]
I have the same problem. My excel file has an image into it and the library is not able to see the image as a'format' that is why it disappears. Has this been rersolved?

**Comment by Apkawa** [comment]
https://openpyxl.readthedocs.io/en/default/usage.html#read-an-existing-workbook
> openpyxl does currently not read all possible items in an Excel file so images and charts will be lost from existing files if they are opened and saved with the same name.

I have not decided how to fix it yet.

**Comment by Apkawa** [comment]
I added a simple image processing method. 
If something is wrong, open a new task with examples
