### ISSUE TITLE
Error while processing merged cells

### ISSUE THREAD

**Issue by matthewrv** [Apkawa/xlsx2html#2]
xlsx2html version: 0.1.5
Python interpreter version: Python 3.8.0
Python interpreter implementation: CPython
Platform: Windows x64

While processing `.xlsx` table with no content but two merged cells next error occurs:
```
>>> xlsx2html('standings.xlsx', 'standings.html')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\venvs\venv_38\lib\site-packages\xlsx2html\core.py", line 264, in xlsx2html
    data = worksheet_to_data(ws, locale='ru')
  File "C:\Users\user\venvs\venv_38\lib\site-packages\xlsx2html\core.py", line 138, in worksheet_to_data
    exclded_cells = set(ws.merged_cells)
TypeError: unhashable type: 'CellRange'
```

**Comment by Apkawa** [comment]
Hello. i'm worked on it. as workaround freeze **openpyxl<2.5**

**Comment by matthewrv** [comment]
@Apkawa, thanks a lot! That helped

**Comment by Apkawa** [comment]
fixed https://github.com/Apkawa/xlsx2html/commit/99ba862c7b07ee5ef29cf7bf6039d93afd31921d
from v0.1.6 can use **openpyxl>2.5**
