### ISSUE TITLE
Accepting stream in input and stream/raw text in output

### ISSUE THREAD

**Issue by eran-pinhas** [Apkawa/xlsx2html#3]
Hi @Apkawa! great job here - Thank you very much!

If it's possible to support not using only `.pdf` file path - I believe I am not the only one using it for web service that does not store the file in the server (S3, HTTP request data etc.) - and the steps of writing it into file and fetching the results back from the disk seems to be redundant. 

In addition - can you explain why not using pixels in style of colgroup -  `width: 218.88in !important;`?

Have a good one,
Eran

**Comment by eran-pinhas** [comment]
Update - currently using
```python
from xlsx2html.core import worksheet_to_data, render_data_to_html

data = worksheet_to_data(worksheet, locale='en')
html = render_data_to_html(data)
```

for me this two functions are super helpful - maybe we should:

1. Combine into single function
2. Adding it to the main package
3. Adding example in README.md

I believe every one of them on it own would be helpful

**Comment by Apkawa** [comment]
xlsx2html==0.1.11

```python
import io
from xlsx2html import xlsx2html

# must be binary mode
xlsx_file = open('path/to/example.xlsx', 'rb') 
out_file = io.StringIO()
xlsx2html(xlsx_file, out_file, locale='en')
out_file.seek(0)
result_html = out_file.read()
```
