### ISSUE TITLE
Cell object is not iterable

### ISSUE THREAD

**Issue by rfish001** [Apkawa/xlsx2html#30]
in file xlsx2html/xlsx2html/core.py  line 171

```py
    for cell_range in merged_cell_ranges:
        cell_range_list = list(ws[cell_range])
        m_cell = cell_range_list[0][0]

```

if i use openpyxl merge only one row data
`merged_cell_range` will like this:
`['A2:A4','A5:A7','B7']`

then ` list(ws[cell_range])` will throw
`Cell object is not iterable`

**Comment by Apkawa** [comment]
Me need example file. i dunno what is bug with merge cell

**Comment by lohithn4** [comment]
[cell_range_value.xlsx](https://github.com/Apkawa/xlsx2html/files/14218439/cell_range_value.xlsx)
@Apkawa added excel file which can cause this issue
