### ISSUE TITLE
Add vertical-align style to cells

### ISSUE THREAD

**Issue by ivanpajares-sploro** [Apkawa/xlsx2html#39]
File: https://github.com/Apkawa/xlsx2html/blob/master/xlsx2html/core.py

Function: `get_styles_from_cell`

Suggested change: add the following code lines:
```
if cell.alignment.vertical:
    h_styles['vertical-align'] = cell.alignment.vertical 
```

**Comment by Apkawa** [comment]
Sorry for the late reply 
in version 0.5.0
