### ISSUE TITLE
Accounting number formatting

### ISSUE THREAD

**Issue by eran-pinhas** [Apkawa/xlsx2html#8]
Hi @Apkawa,

when I'm trying to format an accounting number cell I believe I'm getting wrong formatting of the text.

```
>>> print(cell.number_format)
_(\$* #,##0.00_);_(\$* \(#,##0.00\);_(\$* \-??_);_(@_)

>>> xlsx2html.format.parse_pattern(cell.number_format).apply(12, "en")
' ($ 12.00 )' # should be 12.00$

>>> xlsx2html.format.parse_pattern(cell.number_format).apply(-12, "en")
'- ($ (12.00)' # should be (12.00)$
```

I'll be glad to fix it and open a PR, but I'll need some help understand how to use the rules [here](https://support.office.com/en-us/article/number-format-codes-5026bbd6-04bc-48cd-bf33-80f18b4eae68) to fix the parse_pattern function

Best

**Comment by eran-pinhas** [comment]
I believe I've found 3 issues 

1. instead of `.replace('_', ' ')` we need to `re.sub(... , r'_.', ' ')` for replace the char after the `_` as well
2. this - `neg_prefix = '-' + neg_prefix` seems to be wrong, isn't it? the 2nd part (for negative numbers) should contain the `-` part it want to include it
BTW, there is a comment `  # TODO Do not remove from neg prefix` just before this line, is there a reason not to remove it? 
3. there is no reference to the zero case (except of [this comment](https://github.com/Apkawa/xlsx2html/blob/master/xlsx2html/format.py#L154))

another wrong implementation (which doesn't affect me currently) is that we are not counting for `\` as an escape character and `"asd"` as a fixed string

I'll open a PR for the 1 and 2, but in general I think that it is required to test this

**Comment by Apkawa** [comment]
Hello.
Sorry for late response.
I'm merged it. Me need also add some test cases for that issue.

Thanks anyway

**Comment by eran-pinhas** [comment]
Great, Let me know if you are planning to publish to pypi anytime soon
